// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ueebocnwelhglrpbjqzg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVlZWJvY253ZWxoZ2xycGJqcXpnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3Njg3NTksImV4cCI6MjA3MTM0NDc1OX0.pKNzDtT7La194mE0S_bE0c-wnth67SN-Y6To1aV695g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});